// Skizzen der Katalogübungen: eine SVG-Datei je Übung in public/exercises/.
// Erzeugt mit tools/exercise-art (siehe docs/DESIGN.md, Abschnitt 15).
// Schlüssel ist der Name der globalen Übung, der in der Datenbank eindeutig ist.

export const EXERCISE_IMAGE_SLUGS: Readonly<Record<string, string>> = {
  "Abduktorenmaschine": "abduktorenmaschine",
  "Adduktorenmaschine": "adduktorenmaschine",
  "Air Bike": "air-bike",
  "Arnold Press": "arnold-press",
  "Aufrechtes Rudern": "aufrechtes-rudern",
  "Ausfallschritt": "ausfallschritt",
  "Bankdrücken": "bankdruecken",
  "Bauchroller": "bauchroller",
  "Beinbeuger": "beinbeuger",
  "Beinheben hängend": "beinheben-haengend",
  "Beinheben liegend": "beinheben-liegend",
  "Beinpresse": "beinpresse",
  "Beinstrecker": "beinstrecker",
  "Bizepscurl": "bizepscurl",
  "Box Jump": "box-jump",
  "Brustpresse": "brustpresse",
  "Bulgarian Split Squat": "bulgarian-split-squat",
  "Burpee": "burpee",
  "Butterfly": "butterfly",
  "Copenhagen Plank": "copenhagen-plank",
  "Crosstrainer": "crosstrainer",
  "Crunch": "crunch",
  "Crunch am Kabel": "crunch-am-kabel",
  "Dips": "dips",
  "Enges Bankdrücken": "enges-bankdruecken",
  "Exzentrisches Wadenheben": "exzentrisches-wadenheben",
  "Face Pull": "face-pull",
  "Farmers Walk": "farmers-walk",
  "Fliegende": "fliegende",
  "Frontheben": "frontheben",
  "Frontkniebeuge": "frontkniebeuge",
  "Gehen": "gehen",
  "Glute Bridge": "glute-bridge",
  "Goblet Squat": "goblet-squat",
  "Good Morning": "good-morning",
  "Hackenschmidt-Kniebeuge": "hackenschmidt-kniebeuge",
  "Hammercurl": "hammercurl",
  "Hip Thrust": "hip-thrust",
  "Hollow Hold": "hollow-hold",
  "Isometrischer Beinstrecker": "isometrischer-beinstrecker",
  "Isometrisches Wadenheben": "isometrisches-wadenheben",
  "Kabelcurl": "kabelcurl",
  "Kabelzug-Fliegende": "kabelzug-fliegende",
  "Kettlebell Swing": "kettlebell-swing",
  "Kickback am Kabel": "kickback-am-kabel",
  "Klimmzug": "klimmzug",
  "Klimmzug im Untergriff": "klimmzug-im-untergriff",
  "Kniebeuge": "kniebeuge",
  "Konzentrationscurl": "konzentrationscurl",
  "Kreuzheben": "kreuzheben",
  "Kurzhantel-Bankdrücken": "kurzhantel-bankdruecken",
  "Kurzhantel-Schrägbankdrücken": "kurzhantel-schraegbankdruecken",
  "Kurzhantel-Schulterdrücken": "kurzhantel-schulterdruecken",
  "Kurzhantelcurl": "kurzhantelcurl",
  "Kurzhantelrudern": "kurzhantelrudern",
  "Langhantelrudern": "langhantelrudern",
  "Latzug": "latzug",
  "Laufen": "laufen",
  "Liegestütz": "liegestuetz",
  "Mountain Climber": "mountain-climber",
  "Negativbankdrücken": "negativbankdruecken",
  "Nordic Hamstring Curl": "nordic-hamstring-curl",
  "Pallof Press": "pallof-press",
  "Plank": "plank",
  "Radfahren": "radfahren",
  "Reißen": "reissen",
  "Rudermaschine": "rudermaschine",
  "Rudern": "rudern",
  "Rudern am Kabelzug": "rudern-am-kabelzug",
  "Rumänisches Kreuzheben": "rumaenisches-kreuzheben",
  "Russian Twist": "russian-twist",
  "Rückenstrecker": "rueckenstrecker",
  "Schrägbankdrücken": "schraegbankdruecken",
  "Schulterdrücken": "schulterdruecken",
  "Schulterheben": "schulterheben",
  "Schulterpresse": "schulterpresse",
  "Schwimmen": "schwimmen",
  "Scottcurl": "scottcurl",
  "Seilspringen": "seilspringen",
  "Seitheben": "seitheben",
  "Seitstütz": "seitstuetz",
  "Sit-up": "sit-up",
  "Ski-Ergometer": "ski-ergometer",
  "Spanish Squat": "spanish-squat",
  "Step-up": "step-up",
  "Stirndrücken": "stirndruecken",
  "Sumo-Kreuzheben": "sumo-kreuzheben",
  "T-Bar-Rudern": "t-bar-rudern",
  "Thruster": "thruster",
  "Tibialis-Heben": "tibialis-heben",
  "Treppensteiger": "treppensteiger",
  "Trizeps-Kickback": "trizeps-kickback",
  "Trizepsdrücken am Kabel": "trizepsdruecken-am-kabel",
  "Trizepsdrücken über Kopf": "trizepsdruecken-ueber-kopf",
  "Turkish Get-up": "turkish-get-up",
  "Umsetzen": "umsetzen",
  "Umsetzen und Stoßen": "umsetzen-und-stossen",
  "Unterarmcurl": "unterarmcurl",
  "Vorgebeugtes Seitheben": "vorgebeugtes-seitheben",
  "Wadenheben": "wadenheben",
  "Wadenheben sitzend": "wadenheben-sitzend",
  "Wandsitzen": "wandsitzen",
  "Überzüge": "ueberzuege",
};

/** Pfad zur Skizze einer Übung oder null, wenn es (noch) keine gibt, z. B. bei eigenen Übungen. */
export function exerciseImage(name: string): string | null {
  const slug = Object.hasOwn(EXERCISE_IMAGE_SLUGS, name) ? EXERCISE_IMAGE_SLUGS[name] : undefined;
  return slug ? `/exercises/${slug}.svg` : null;
}
