-- O-Health-Plattform · Migration 0010
-- Übungskatalog für den Alltag: gut hundert gängige Übungen mit den Namen, die im
-- deutschen Studio üblich sind, dazu Suchbegriffe (englische und alternative Namen).
--
-- Die zwölf bisherigen Übungen bleiben mit ihrer ID erhalten und werden nur ergänzt.

alter table public.exercises
  add column aliases text[] not null default '{}';

insert into public.exercises (name, muscle_group, category, measure, is_global, created_by, aliases) values
  -- Brust
  ('Bankdrücken',                 'Brust', 'strength', 'weight_reps', true, null, '{Bench Press,Flachbankdrücken}'),
  ('Schrägbankdrücken',           'Brust', 'strength', 'weight_reps', true, null, '{Incline Bench Press}'),
  ('Negativbankdrücken',          'Brust', 'strength', 'weight_reps', true, null, '{Decline Bench Press}'),
  ('Kurzhantel-Bankdrücken',      'Brust', 'strength', 'weight_reps', true, null, '{Dumbbell Bench Press,KH-Bankdrücken}'),
  ('Kurzhantel-Schrägbankdrücken','Brust', 'strength', 'weight_reps', true, null, '{Incline Dumbbell Press}'),
  ('Brustpresse',                 'Brust', 'strength', 'weight_reps', true, null, '{Chest Press,Maschine}'),
  ('Fliegende',                   'Brust', 'strength', 'weight_reps', true, null, '{Flys,Kurzhantel-Flys,Dumbbell Fly}'),
  ('Butterfly',                   'Brust', 'strength', 'weight_reps', true, null, '{Pec Deck,Maschine}'),
  ('Kabelzug-Fliegende',          'Brust', 'strength', 'weight_reps', true, null, '{Cable Crossover,Cable Fly}'),
  ('Liegestütz',                  'Brust', 'strength', 'weight_reps', true, null, '{Push-up,Pushup}'),
  ('Dips',                        'Brust', 'strength', 'weight_reps', true, null, '{Barrenstütz}'),
  -- Rücken
  ('Kreuzheben',                  'Rücken', 'strength', 'weight_reps', true, null, '{Deadlift}'),
  ('Sumo-Kreuzheben',             'Rücken', 'strength', 'weight_reps', true, null, '{Sumo Deadlift}'),
  ('Klimmzug',                    'Rücken', 'strength', 'weight_reps', true, null, '{Pull-up,Pullup}'),
  ('Klimmzug im Untergriff',      'Rücken', 'strength', 'weight_reps', true, null, '{Chin-up,Chinup}'),
  ('Latzug',                      'Rücken', 'strength', 'weight_reps', true, null, '{Lat Pulldown,Latziehen}'),
  ('Langhantelrudern',            'Rücken', 'strength', 'weight_reps', true, null, '{Barbell Row,Bent-over Row}'),
  ('Kurzhantelrudern',            'Rücken', 'strength', 'weight_reps', true, null, '{Dumbbell Row,Einarmiges Rudern}'),
  ('Rudern am Kabelzug',          'Rücken', 'strength', 'weight_reps', true, null, '{Seated Cable Row,Kabelrudern}'),
  ('T-Bar-Rudern',                'Rücken', 'strength', 'weight_reps', true, null, '{T-Bar Row}'),
  ('Rudermaschine',               'Rücken', 'strength', 'weight_reps', true, null, '{Machine Row,Maschinenrudern}'),
  ('Überzüge',                    'Rücken', 'strength', 'weight_reps', true, null, '{Pullover}'),
  ('Rückenstrecker',              'Rücken', 'strength', 'weight_reps', true, null, '{Hyperextension,Back Extension}'),
  ('Good Morning',                'Rücken', 'strength', 'weight_reps', true, null, '{Rumpfbeugen}'),
  ('Schulterheben',               'Rücken', 'strength', 'weight_reps', true, null, '{Shrugs,Nacken}'),
  -- Schultern
  ('Schulterdrücken',             'Schultern', 'strength', 'weight_reps', true, null, '{Overhead Press,OHP,Military Press}'),
  ('Kurzhantel-Schulterdrücken',  'Schultern', 'strength', 'weight_reps', true, null, '{Dumbbell Shoulder Press}'),
  ('Arnold Press',                'Schultern', 'strength', 'weight_reps', true, null, '{Arnold-Drücken}'),
  ('Schulterpresse',              'Schultern', 'strength', 'weight_reps', true, null, '{Shoulder Press,Maschine}'),
  ('Seitheben',                   'Schultern', 'strength', 'weight_reps', true, null, '{Lateral Raise}'),
  ('Frontheben',                  'Schultern', 'strength', 'weight_reps', true, null, '{Front Raise}'),
  ('Vorgebeugtes Seitheben',      'Schultern', 'strength', 'weight_reps', true, null, '{Reverse Fly,Rear Delt Fly}'),
  ('Face Pull',                   'Schultern', 'strength', 'weight_reps', true, null, '{Facepull}'),
  ('Aufrechtes Rudern',           'Schultern', 'strength', 'weight_reps', true, null, '{Upright Row}'),
  -- Arme
  ('Bizepscurl',                  'Arme', 'strength', 'weight_reps', true, null, '{Curl,Langhantelcurl,Barbell Curl}'),
  ('Kurzhantelcurl',              'Arme', 'strength', 'weight_reps', true, null, '{Dumbbell Curl}'),
  ('Hammercurl',                  'Arme', 'strength', 'weight_reps', true, null, '{Hammer Curl}'),
  ('Scottcurl',                   'Arme', 'strength', 'weight_reps', true, null, '{Preacher Curl}'),
  ('Konzentrationscurl',          'Arme', 'strength', 'weight_reps', true, null, '{Concentration Curl}'),
  ('Kabelcurl',                   'Arme', 'strength', 'weight_reps', true, null, '{Cable Curl}'),
  ('Trizepsdrücken am Kabel',     'Arme', 'strength', 'weight_reps', true, null, '{Pushdown,Triceps Pushdown}'),
  ('Trizepsdrücken über Kopf',    'Arme', 'strength', 'weight_reps', true, null, '{Overhead Triceps Extension}'),
  ('Stirndrücken',                'Arme', 'strength', 'weight_reps', true, null, '{Skull Crusher,French Press}'),
  ('Enges Bankdrücken',           'Arme', 'strength', 'weight_reps', true, null, '{Close-Grip Bench Press}'),
  ('Trizeps-Kickback',            'Arme', 'strength', 'weight_reps', true, null, '{Kickback}'),
  ('Unterarmcurl',                'Arme', 'strength', 'weight_reps', true, null, '{Wrist Curl}'),
  -- Beine
  ('Kniebeuge',                   'Beine', 'strength', 'weight_reps', true, null, '{Squat,Back Squat}'),
  ('Frontkniebeuge',              'Beine', 'strength', 'weight_reps', true, null, '{Front Squat}'),
  ('Goblet Squat',                'Beine', 'strength', 'weight_reps', true, null, '{Goblet-Kniebeuge}'),
  ('Beinpresse',                  'Beine', 'strength', 'weight_reps', true, null, '{Leg Press}'),
  ('Hackenschmidt-Kniebeuge',     'Beine', 'strength', 'weight_reps', true, null, '{Hack Squat}'),
  ('Ausfallschritt',              'Beine', 'strength', 'weight_reps', true, null, '{Lunge,Lunges}'),
  ('Bulgarian Split Squat',       'Beine', 'strength', 'weight_reps', true, null, '{Bulgarische Kniebeuge}'),
  ('Step-up',                     'Beine', 'strength', 'weight_reps', true, null, '{Aufsteiger}'),
  ('Beinstrecker',                'Beine', 'strength', 'weight_reps', true, null, '{Leg Extension}'),
  ('Beinbeuger',                  'Beine', 'strength', 'weight_reps', true, null, '{Leg Curl}'),
  ('Rumänisches Kreuzheben',      'Beine', 'strength', 'weight_reps', true, null, '{RDL,Romanian Deadlift}'),
  ('Nordic Hamstring Curl',       'Beine', 'strength', 'weight_reps', true, null, '{Nordic Curl}'),
  ('Wadenheben',                  'Beine', 'strength', 'weight_reps', true, null, '{Calf Raise}'),
  ('Wadenheben sitzend',          'Beine', 'strength', 'weight_reps', true, null, '{Seated Calf Raise}'),
  ('Adduktorenmaschine',          'Beine', 'strength', 'weight_reps', true, null, '{Adductor}'),
  ('Abduktorenmaschine',          'Beine', 'strength', 'weight_reps', true, null, '{Abductor}'),
  ('Box Jump',                    'Beine', 'strength', 'weight_reps', true, null, '{Kastensprung}'),
  ('Wandsitzen',                  'Beine', 'strength', 'duration',    true, null, '{Wall Sit}'),
  -- Gesäß
  ('Hip Thrust',                  'Gesäß', 'strength', 'weight_reps', true, null, '{Hüftstoß}'),
  ('Glute Bridge',                'Gesäß', 'strength', 'weight_reps', true, null, '{Beckenheben,Brücke}'),
  ('Kickback am Kabel',           'Gesäß', 'strength', 'weight_reps', true, null, '{Cable Kickback,Glute Kickback}'),
  -- Rumpf
  ('Plank',                       'Rumpf', 'strength', 'duration',    true, null, '{Unterarmstütz}'),
  ('Seitstütz',                   'Rumpf', 'strength', 'duration',    true, null, '{Side Plank}'),
  ('Hollow Hold',                 'Rumpf', 'strength', 'duration',    true, null, '{Hollow Body}'),
  ('Copenhagen Plank',            'Rumpf', 'strength', 'duration',    true, null, '{Kopenhagener Plank,Adduktoren}'),
  ('Crunch',                      'Rumpf', 'strength', 'weight_reps', true, null, '{Bauchpresse}'),
  ('Sit-up',                      'Rumpf', 'strength', 'weight_reps', true, null, '{Situp}'),
  ('Crunch am Kabel',             'Rumpf', 'strength', 'weight_reps', true, null, '{Cable Crunch}'),
  ('Beinheben hängend',           'Rumpf', 'strength', 'weight_reps', true, null, '{Hanging Leg Raise}'),
  ('Beinheben liegend',           'Rumpf', 'strength', 'weight_reps', true, null, '{Leg Raise}'),
  ('Russian Twist',               'Rumpf', 'strength', 'weight_reps', true, null, '{Russischer Twist}'),
  ('Bauchroller',                 'Rumpf', 'strength', 'weight_reps', true, null, '{Ab Wheel,Ab Roller}'),
  ('Pallof Press',                'Rumpf', 'strength', 'weight_reps', true, null, '{Anti-Rotation}'),
  ('Mountain Climber',            'Rumpf', 'strength', 'weight_reps', true, null, '{Bergsteiger}'),
  -- Ganzkörper
  ('Burpee',                      'Ganzkörper', 'strength', 'weight_reps', true, null, '{Burpees}'),
  ('Kettlebell Swing',            'Ganzkörper', 'strength', 'weight_reps', true, null, '{Kettlebell-Schwung}'),
  ('Umsetzen',                    'Ganzkörper', 'strength', 'weight_reps', true, null, '{Clean,Power Clean}'),
  ('Umsetzen und Stoßen',         'Ganzkörper', 'strength', 'weight_reps', true, null, '{Clean and Jerk}'),
  ('Reißen',                      'Ganzkörper', 'strength', 'weight_reps', true, null, '{Snatch}'),
  ('Thruster',                    'Ganzkörper', 'strength', 'weight_reps', true, null, '{Kniebeuge mit Drücken}'),
  ('Turkish Get-up',              'Ganzkörper', 'strength', 'weight_reps', true, null, '{Türkisches Aufstehen}'),
  ('Farmers Walk',                'Ganzkörper', 'strength', 'distance',    true, null, '{Farmers Carry,Bauerngang}'),
  -- Ausdauer
  ('Laufen',                      'Ausdauer', 'cardio', 'distance', true, null, '{Joggen,Running,Laufband}'),
  ('Gehen',                       'Ausdauer', 'cardio', 'distance', true, null, '{Walking,Spazieren}'),
  ('Radfahren',                   'Ausdauer', 'cardio', 'distance', true, null, '{Cycling,Fahrrad,Ergometer}'),
  ('Rudern',                      'Ausdauer', 'cardio', 'distance', true, null, '{Ruderergometer,Rowing}'),
  ('Schwimmen',                   'Ausdauer', 'cardio', 'distance', true, null, '{Swimming}'),
  ('Ski-Ergometer',               'Ausdauer', 'cardio', 'distance', true, null, '{SkiErg}'),
  ('Crosstrainer',                'Ausdauer', 'cardio', 'duration', true, null, '{Ellipsentrainer,Elliptical}'),
  ('Treppensteiger',              'Ausdauer', 'cardio', 'duration', true, null, '{Stairmaster,Stepper}'),
  ('Air Bike',                    'Ausdauer', 'cardio', 'duration', true, null, '{Assault Bike}'),
  ('Seilspringen',                'Ausdauer', 'cardio', 'duration', true, null, '{Jump Rope,Springseil}'),
  -- Reha und Sehnen
  ('Isometrisches Wadenheben',    'Beine', 'rehab', 'duration',    true, null, '{Achillessehne,Isometric Calf Raise}'),
  ('Exzentrisches Wadenheben',    'Beine', 'rehab', 'weight_reps', true, null, '{Achillessehne,Eccentric Calf Raise}'),
  ('Spanish Squat',               'Beine', 'rehab', 'duration',    true, null, '{Patellasehne,Spanische Kniebeuge}'),
  ('Isometrischer Beinstrecker',  'Beine', 'rehab', 'duration',    true, null, '{Patellasehne,Isometric Leg Extension}'),
  ('Tibialis-Heben',              'Beine', 'rehab', 'weight_reps', true, null, '{Tibialis Raise,Schienbein}')
on conflict (lower(name)) where is_global do update
  set muscle_group = excluded.muscle_group,
      category     = excluded.category,
      measure      = excluded.measure,
      aliases      = excluded.aliases;
